### ISSUE TITLE
Invalid custom element names generated on Windows

### ISSUE THREAD

**Issue by danjunger** [cardoso/vite-plugin-lwc#1]
Using a dynamic component via `lwc:is` breaks on a Windows machine using vite-plugin-lwc where the same code works in a Mac environment. Errors like this are thrown:

```
Failed to execute 'define' on 'CustomElementRegistry': "d:/dev/src/demo_app/src/modules/demo_app/demo-" is not a valid custom element name
```

It seems the path is being translated into a name, but those names on Windows contain illegal characters. I had initially thought that this code https://github.com/cardoso/vite-plugin-lwc/blob/main/packages/cem-plugin-lwc/src/module.ts#L4 might be responsible for that, but I don't see this code in the  `index.mjs` of the distributed vite-plugin-lwc library.

**Comment by cardoso** [comment]
@danjunger thanks for opening this issue! The cem-plugin-lwc is just an experiment separate from the vite-plugin-lwc, so it shouldn't cause any issue here.

Would you be able to provide a minimal reproduction?

**Comment by danjunger** [comment]
hey @cardoso, i made a quick repro case and verified it with a colleague who's using windows.

- clone the repo here https://github.com/danjunger/vite-repro
- checkout branch `djunger/windows-repro`
- `npm install`
- `npm run dev`

On Windows, the LWC app will fail to load with an error like this in the javascript console:
![image (2)](https://github.com/user-attachments/assets/5a46f295-ee2a-43d6-90b5-48abaa717b30)

On Mac, the LWC app loads correctly and looks like this (and the button is clickable to toggle the dynamic component)

<img width="395" alt="Screenshot 2024-12-10 at 9 51 48 AM" src="https://github.com/user-attachments/assets/4204d0e8-28a2-4c32-b5b3-e48b4bc3f395">

**Comment by cardoso** [comment]
Thanks @danjunger ! I'll see if I can set up some kind of Windows VM to debug this.

**Comment by danjunger** [comment]
closing this as the problem seems to stem from an issue in lwc-rollup-plugin: https://github.com/salesforce/lwc/pull/5038
